# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6ebbb33c-59fd-4174-88a8-188370bab79d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/65A4-0C28";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1e3fae3e-a834-4e1b-b933-609305219022";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1d3f8eff-57f1-49fa-994d-3d5c07b60234";
      fsType = "ext4";
    };

  fileSystems."/media/master" =
    { device = "/dev/disk/by-uuid/42c4e372-48bd-4973-99ea-af8718526293";
      fsType = "ext4";
    };

  fileSystems."/media/secondary" =
    { device = "/dev/disk/by-uuid/40427651-d147-4d21-afc6-4a0cd3705ef6";
      fsType = "ext4";
    };

  fileSystems."/media/backup" =
    { device = "/dev/disk/by-uuid/baca06df-55db-4c73-a7cc-177871b93b14";
      fsType = "ext4";
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/761bac1f-79e0-4e9f-8649-94c82dc4da9f";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5aa5bdb4-cea1-4df0-a2cb-19afececb667"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
