#!/usr/bin/env bash

# ~/.config/bash/aliases

##################
## Bash Aliases ##
##################

# Drop-in program replacements
alias ls='exa -G --color=always --icons'                                # replace `ls` with `exa` (faster, written in Rust)
alias vi='nvim'                                                         # replace `vi` with `nvim` (because `vi` is for grandpas and hipsters)
alias visudo='sudo -i vim'
alias find='fd'                                                         # replace `find` with `fd` (faster, written in -- you guessed it -- Rust)

# Navigation
alias lt='exa =TL 2'
alias lsa='exa -alu --git --time-style long-iso'                        # more info about hidden files (w/ git status)
alias lsd='exa -D'                                                      # list only directories

# Terminal clearing
alias cl='clear'                                                        # because typing `clear` just takes too long
alias cdd='cd; clear; sleep 0.01; exa -xDG'                             # teleport to $HOME
alias cdc='cd ~/.config; clear; exa -D'                                 # teleport to $HOME/.config/
alias cdn='cd ~/.config/nixos; clear; exa'                              # teleport to $HOME/.config/nixos/ (NixOS config directory)
