#!/usr/bin/env bash

# ~/.config/bash/aliases

##################
## Bash Aliases ##
##################

# Drop-in program replacements
alias ls='exa -G --color=always --icons'                                # replace `ls` with `exa` (faster, written in Rust)
alias find='fd'                                                         # replace `find` with `fd` (faster, written in -- you guessed it -- Rust)

# Navigation
alias lsa='exa -Galu --git --time-style long-iso'                        # more info about hidden files (w/ git status)
alias lsd='exa -D'                                                      # list only directories

# Terminal clearing
alias cl='clear'                                                        # because typing `clear` just takes too long

# Teleport to $HOME
cdd () {
    cd $HOME
    clear
    sleep 0.01
    exa -xDG
}

# Teleport to ~/.config
cdc () {
    cd $HOME/.config
    clear
    exa -D
}

# Teleport to NixOS configuration directory
cdn () {
    cd $HOME/.config/nixos/
    clear
    exa
}

# Quicker access to `git status`
ghs () {
    git status
}

# Quickly transform all images in the current directory into PNG files
pngify () {
    if [[ $# = 0 ]]
    then
        command mogrify -format png *.jpg *.jpeg *.webp
    else
        command mogrify -format png "$@"
    fi
}
