#!/usr/bin/env bash

# ~/.config/bash/bashrc

[[ -f ~/.config/bash/aliases ]] && . ~/.config/bash/aliases

# Enable Starship prompt
eval "$(starship init bash)"

# Teleport to $HOME
cdd () {
    cd ${HOME}
    clear
    sleep 0.01
    command eza -xDG --icons
}

# Teleport to config directory
cdc () {
    cd ${XDG_CONFIG_HOME}
    clear
    command eza -D --icons
}

# Teleport to NixOS configuration directory
cdn () {
    cd ${HOME}/.nixos
    clear
    command eza --icons
}

# `gh` wrapper to make listing issues easier
gh () {
    if [[ $@ == "issue list" ]]; then
        command gh issue list -L 100
    else
        command gh "$@"
    fi
}

